server:
  port: 0

spring:

  application:
    name: accounts-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:accounts-db
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9094
      - localhost:9096

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all

      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        allow.auto.create.topics: false

    consumer:
      group-id: accounts-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: io.eddie.core.*
        allow.auto.create.topics: false



accounts:

  config:
    topic-partitions: 3
    topic-replications: 3

  commands:
    topic:
      name: accounts-commands

  events:
    topic:
      name: accounts-events

carts:

  events:
    topic:
      name: carts-events

  commands:
    topic:
      name: carts-commands

deposits:

  events:
    topic:
      name: deposits-events

  commands:
    topic:
      name: deposits-commands


custom:

  jwt:
    secrets:
      app-key: A5A10BC17B4E653C78BDD55FFFD9DEE3BE5790CD6F3F64DC1E82E791F9821C17
    expiration: 600000000


eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.uuid}"
